
import React, { useState, useMemo } from 'react';
import { Product, AuthUser } from '../types';

interface ProductsProps {
  products: Product[];
  onAdd: (product: Product) => void;
  onUpdate: (product: Product) => void;
  onDelete: (id: string) => void;
  globalSearchQuery?: string;
  user?: AuthUser | null;
}

const Products: React.FC<ProductsProps> = ({ products, onAdd, onUpdate, onDelete, globalSearchQuery = '', user }) => {
  const [isAdding, setIsAdding] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [productForm, setProductForm] = useState<Partial<Product>>({
    name: '',
    price: 0,
    stock: 0,
    description: ''
  });

  const isAdmin = user?.role === 'Admin';

  const filteredProducts = useMemo(() => {
    if (!globalSearchQuery) return products;
    const q = globalSearchQuery.toLowerCase().trim();
    return products.filter(p => 
      p.name.toLowerCase().includes(q)
    );
  }, [products, globalSearchQuery]);

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!isAdmin) return;
    if (!productForm.name || productForm.price === undefined || productForm.stock === undefined) return;
    
    if (editingId) {
      onUpdate({
        ...productForm,
        id: editingId,
        name: productForm.name,
        price: Number(productForm.price),
        stock: Number(productForm.stock),
        description: productForm.description || '',
        createdAt: products.find(p => p.id === editingId)?.createdAt || new Date().toISOString()
      } as Product);
    } else {
      onAdd({
        id: Math.random().toString(36).substr(2, 9),
        name: productForm.name,
        price: Number(productForm.price),
        stock: Number(productForm.stock),
        description: productForm.description || '',
        createdAt: new Date().toISOString()
      });
    }
    resetForm();
  };

  const resetForm = () => {
    setProductForm({ name: '', price: 0, stock: 0, description: '' });
    setIsAdding(false);
    setEditingId(null);
  };

  const handleEdit = (product: Product) => {
    if (!isAdmin) return;
    setProductForm({
      name: product.name,
      price: product.price,
      stock: product.stock,
      description: product.description
    });
    setEditingId(product.id);
    setIsAdding(true);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleExportAll = () => {
    if (!isAdmin) return;
    if (products.length === 0) return alert("No products to export.");

    const element = document.createElement('div');
    element.style.padding = '40px';
    element.style.fontFamily = 'Inter, sans-serif';
    element.innerHTML = `
      <div style="margin-bottom: 30px; border-bottom: 2px solid #000; padding-bottom: 15px;">
        <h1 style="font-size: 24px; font-weight: 900; margin: 0;">WARRICK PRODUCT INVENTORY</h1>
        <p style="font-size: 10px; color: #666; font-weight: 800; text-transform: uppercase; letter-spacing: 2px;">Full Catalog Export • ${new Date().toLocaleDateString()}</p>
      </div>
      <table style="width: 100%; border-collapse: collapse; font-size: 12px;">
        <thead>
          <tr style="background: #f4f4f4;">
            <th style="border: 1px solid #ddd; padding: 10px; text-align: left;">PRODUCT NAME</th>
            <th style="border: 1px solid #ddd; padding: 10px; text-align: left;">PRICE (BDT)</th>
            <th style="border: 1px solid #ddd; padding: 10px; text-align: left;">STOCK LEVEL</th>
          </tr>
        </thead>
        <tbody>
          ${products.map(p => `
            <tr>
              <td style="border: 1px solid #ddd; padding: 10px; font-weight: 700; text-transform: uppercase;">${p.name}</td>
              <td style="border: 1px solid #ddd; padding: 10px;">৳ ${p.price.toLocaleString()}</td>
              <td style="border: 1px solid #ddd; padding: 10px; color: ${p.stock <= 10 ? '#ef4444' : '#000'}">${p.stock}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
      <div style="margin-top: 30px; text-align: center; color: #999; font-size: 9px; font-weight: 800;">
        GENERATED BY WARRICK INTELLIGENCE SYSTEM
      </div>
    `;

    const opt = {
      margin: 10,
      filename: `Warrick_Inventory_${new Date().toISOString().split('T')[0]}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    // @ts-ignore
    window.html2pdf().from(element).set(opt).save();
  };

  const handleExportSingle = (product: Product) => {
    if (!isAdmin) return;
    
    const element = document.createElement('div');
    element.style.padding = '60px';
    element.style.fontFamily = 'Inter, sans-serif';
    element.innerHTML = `
      <div style="border: 2px solid #000; padding: 40px; background: #fff;">
        <div style="margin-bottom: 40px; text-align: center;">
          <h1 style="font-size: 28px; font-weight: 900; margin: 0; letter-spacing: -1px;">PRODUCT SPECIFICATION</h1>
          <p style="font-size: 10px; color: #666; font-weight: 800; text-transform: uppercase; letter-spacing: 3px; margin-top: 5px;">Inventory Record</p>
        </div>
        
        <div style="margin-bottom: 30px;">
          <label style="font-size: 10px; font-weight: 900; color: #999; text-transform: uppercase;">Item Designation</label>
          <div style="font-size: 22px; font-weight: 900; color: #000; margin-top: 5px; border-bottom: 1px solid #eee; padding-bottom: 10px; text-transform: uppercase;">${product.name}</div>
        </div>

        <div style="display: grid; grid-template-cols: 1fr 1fr; gap: 40px; margin-bottom: 40px;">
          <div>
            <label style="font-size: 10px; font-weight: 900; color: #999; text-transform: uppercase;">Unit Valuation</label>
            <div style="font-size: 20px; font-weight: 900; color: #000; margin-top: 5px;">৳ ${product.price.toLocaleString()}</div>
          </div>
          <div>
            <label style="font-size: 10px; font-weight: 900; color: #999; text-transform: uppercase;">Current Stock</label>
            <div style="font-size: 20px; font-weight: 900; color: ${product.stock <= 10 ? '#ef4444' : '#000'}; margin-top: 5px;">${product.stock} Units</div>
          </div>
        </div>

        ${product.description ? `
          <div style="margin-bottom: 40px;">
            <label style="font-size: 10px; font-weight: 900; color: #999; text-transform: uppercase;">Technical Details</label>
            <div style="font-size: 14px; font-weight: 500; color: #444; margin-top: 5px; line-height: 1.6;">${product.description}</div>
          </div>
        ` : ''}

        <div style="border-top: 1px dashed #ccc; padding-top: 20px; display: flex; justify-content: space-between; align-items: center;">
          <div>
            <p style="font-size: 8px; font-weight: 900; color: #aaa; text-transform: uppercase;">Stock Code</p>
            <p style="font-size: 9px; font-weight: 700; color: #000;">${product.id}</p>
          </div>
          <div style="text-align: right;">
            <p style="font-size: 8px; font-weight: 900; color: #aaa; text-transform: uppercase;">Record Updated</p>
            <p style="font-size: 9px; font-weight: 700; color: #000;">${new Date(product.createdAt).toLocaleDateString()}</p>
          </div>
        </div>
        
        <div style="margin-top: 60px; text-align: center; border-top: 2px solid #000; padding-top: 20px;">
          <p style="font-size: 9px; font-weight: 900; color: #000; letter-spacing: 2px;">WARRICK INTELLIGENCE SYSTEM</p>
        </div>
      </div>
    `;

    const opt = {
      margin: 10,
      filename: `Product_${product.name.replace(/\s+/g, '_')}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    // @ts-ignore
    window.html2pdf().from(element).set(opt).save();
  };

  return (
    <div className="w-full space-y-12 animate-in slide-in-from-bottom-4 duration-700 pb-20">
      <div className="flex flex-col md:flex-row justify-between items-center gap-8">
        <div className="text-center md:text-left">
          <h1 className="text-[30px] font-black tracking-tighter text-[#1F2937] dark:text-white leading-none mb-4">
            WARRICK<span className="text-black dark:text-blue-500">.</span>
          </h1>
          <div className="relative inline-block group">
             <div className="bg-white/60 dark:bg-white/5 px-4 py-1.5 rounded-full border border-white/40 mt-1 shadow-sm">
                <p className="text-[10px] font-black text-[#4B5563] dark:text-gray-400 uppercase tracking-[0.2em]">
                  POWERED BY ARVIN
                </p>
             </div>
          </div>
        </div>

        <div className="flex items-center space-x-4">
          {isAdmin && (
            <>
              <button 
                onClick={handleExportAll}
                className="tactile-btn px-8 py-4 bg-white text-green-600 border-none"
              >
                Export All
              </button>
              <button 
                onClick={() => {
                  if (isAdding) resetForm();
                  else setIsAdding(true);
                }}
                className={`tactile-btn px-10 py-4 ${
                  isAdding ? 'bg-gray-100 text-gray-400' : ''
                }`}
              >
                {isAdding ? 'Dismiss' : 'New Product'}
              </button>
            </>
          )}
        </div>
      </div>

      {isAdding && isAdmin && (
        <div className="flex justify-center w-full animate-in fade-in zoom-in-95 duration-500">
          <form 
            onSubmit={handleFormSubmit} 
            className="clay-card p-8 md:p-12 w-full max-w-3xl"
          >
            <div className="flex items-center space-x-4 mb-10">
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="md:col-span-2 space-y-2">
                <label className="text-[10px] font-black text-gray-500 ml-4 uppercase tracking-widest">PRODUCT NAME</label>
                <div className="sunken-well px-8 py-5">
                  <input
                    required
                    type="text"
                    className="bg-transparent w-full outline-none font-bold text-gray-800 dark:text-white uppercase"
                    value={productForm.name}
                    onChange={(e) => setProductForm({ ...productForm, name: e.target.value })}
                  />
                </div>
              </div>
              <div className="space-y-2">
                <label className="text-[10px] font-black text-gray-500 ml-4 uppercase tracking-widest">Price</label>
                <div className="sunken-well px-8 py-5">
                  <input
                    required
                    type="number"
                    className="bg-transparent w-full outline-none font-bold text-gray-800 dark:text-white"
                    value={productForm.price}
                    onChange={(e) => setProductForm({ ...productForm, price: Number(e.target.value) })}
                  />
                </div>
              </div>
              <div className="space-y-2">
                <label className="text-[10px] font-black text-gray-500 ml-4 uppercase tracking-widest">Quantity (Stock)</label>
                <div className="sunken-well px-8 py-5">
                  <input
                    required
                    type="number"
                    className="bg-transparent w-full outline-none font-bold text-gray-800 dark:text-white"
                    value={productForm.stock}
                    onChange={(e) => setProductForm({ ...productForm, stock: Number(e.target.value) })}
                  />
                </div>
              </div>
            </div>
            <div className="mt-10 flex justify-end space-x-4">
              <button 
                type="submit" 
                className="tactile-btn bg-black text-white px-10 py-4"
              >
                {editingId ? 'Update Product' : 'Save Product'}
              </button>
            </div>
          </form>
        </div>
      )}

      <div className="space-y-6">
        <div className="clay-card overflow-hidden">
          <div className="divide-y divide-gray-100 dark:divide-gray-800">
            {filteredProducts.length === 0 ? (
              <div className="p-24 text-center">
                <p className="text-gray-400 font-black italic tracking-widest text-xs uppercase opacity-40">
                  {globalSearchQuery ? `NO MATCHES FOR "${globalSearchQuery}"` : 'NO PRODUCTS LISTED'}
                </p>
              </div>
            ) : (
              filteredProducts.map((product) => (
                <div key={product.id} className="p-10 flex items-center justify-between bg-[#E3F2FD] dark:bg-[#1E293B] hover:opacity-90 transition-all cursor-pointer group">
                  <div className="flex items-center space-x-8">
                    <div className="w-16 h-16 rounded-full tactile-btn !p-0 bg-[#F8F9FA] dark:bg-[#1A1C1E]">
                      <span className="font-black text-2xl text-gray-400">{product.name.charAt(0)}</span>
                    </div>
                    <div>
                      <h4 className="font-black text-2xl text-gray-800 dark:text-gray-200 tracking-tight uppercase">{product.name}</h4>
                      <div className="flex items-center space-x-4 mt-1">
                        <span className="text-xs font-bold text-black dark:text-white tracking-widest uppercase font-black">৳ {product.price.toLocaleString()}</span>
                        <span className={`text-[10px] font-black px-3 py-0.5 rounded-full uppercase tracking-tighter ${product.stock > 10 ? 'bg-green-100 text-green-600' : 'bg-red-100 text-red-600'}`}>
                          STOCK: {product.stock}
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center space-x-4">
                    {isAdmin && (
                      <>
                        <button 
                          onClick={(e) => { e.stopPropagation(); handleExportSingle(product); }} 
                          className="tactile-btn !p-3 text-green-600"
                          title="Export Product Details"
                        >
                          Export
                        </button>
                        <button onClick={(e) => { e.stopPropagation(); handleEdit(product); }} className="tactile-btn !p-3 text-blue-500">Edit</button>
                        <button onClick={(e) => { e.stopPropagation(); onDelete(product.id); }} className="tactile-btn !p-3 text-red-500">Delete</button>
                      </>
                    )}
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Products;
